spring.application.name=HotelView

spring.data.mongodb.uri=mongodb+srv://HotelViewAdmin:Y8IJEGg4oMRiWCSR@cluster0.erqacfy.mongodb.net/HotelView?retryWrites=true&w=majority

//spring.data.mongodb.uri=${MONGO_DB_URI}