spring.application.name=HotelView

# MongoDB connection (read from environment variable)
spring.data.mongodb.uri=${MONGO_DB_URI}

# JWT secret (read from environment variable)
jwt.secret=${JWT_SECRET}

# Server port
server.port=8080

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false

spring.profiles.active=dev

//Railway
## Tell Spring to use Caffeine as the cache provider
#spring.cache.type=caffeine
#
## Configure cache metrics: hold up to 500 hotels simultaneously,
## and keep them cached for 24 hours from the last time they were accessed.
#spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=24h

//Render
spring.cache.type=caffeine

# Perfect for your test scale: hold up to 10 hotels safely,
# and keep them in memory for 1 hour from their last access.
spring.cache.caffeine.spec=maximumSize=10,expireAfterAccess=1h